name: Release

on: push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4    
    - name: Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: projetoscti.com.br
        port: 4026
        username: eq2ini3a
        password: eq33a996
        local_path: ./
        remote_path: /var/www/html/eq2.ini3a
        sftp_only: true
